# Configuration des pipelines (chemins de données)
pipelines:
  brest:
    data:
      input: "data/brest"    # Répertoire contenant les CSV/Parquet PMSI (source SNDS)
      output: "scenarios/brest/" # Répertoire de sortie des scenarios générés
  aphp:
    data:
      input: "data/aphp"     # Répertoire contenant les CSV/Parquet PMSI (source ATIH)
      output: "scenarios/aphp/" # Répertoire de sortie des scenarios générés
      referentials: "data/aphp/referentials" # Référentiels AP-HP